# Generated by Django 2.0 on 2019-03-25 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='wishlist',
            new_name='wishlisted',
        ),
    ]
